### ISSUE TITLE
Version 2.23

### ISSUE THREAD

**Issue by DavidBeale** [abachar/chrome-driver-standalone#1]
Hi,

Really useful module.

Any chance you can add version 2.23, for use with an old version of Chome?

thanks,

  David

**Comment by abachar** [comment]
Hi, 
Of course i will add 2.23, 2.24 and the last version 2.28 by the end of this week

**Comment by DavidBeale** [comment]
Great, thanks

**Comment by abachar** [comment]
I released version [2.23](https://github.com/abachar/chrome-driver-standalone/releases/tag/2.23), now you can install it with ```npm install chrome-driver-standalone@2.23.0```

Thank you for your contribution.
